### ISSUE TITLE
Railsアプリケーションのファイル保存先をS3に向ける

### ISSUE THREAD

**Issue by yukihigaa** [yukihigaa/S3_Activestorage_practice#5]

**Comment by yukihigaa** [comment]
# config/storage.ymlをいじって保存先をS3に向ける
[Railsガイド](https://railsguides.jp/active_storage_overview.html)
今回もRailsガイドに沿って設定していきます！

config/storage.ymlには初めから
amazon ⇨ S3
google ⇨ GCS
microsoft ⇨ AzureStorage
と、各主要のCloudストレージサービスの設定が記述されています！便利ー！
今回はAmazonが提供しているS3サービスを使うので
```
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-1
  bucket: your_own_bucket
```
の部分のコメントアウトを外します！
<img width="733" alt="スクリーンショット 2020-05-06 22 31 23" src="https://user-images.githubusercontent.com/56257108/81182876-56861080-8fe9-11ea-943b-db16bab3aa42.png">
